---
apiVersion: v1
kind: Namespace
metadata:
  name: awx
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  service_type: ClusterIP
  ingress_type: none

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: awx-server
  namespace: awx
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`awx.humlevagen`)
      priority: 10
      services:
        - name: awx-demo-service
          port: 80
  tls:
    certResolver: default
    options:
      name: opt
