---
apiVersion: v1
kind: Namespace
metadata:
  name: awx
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  service_type: ClusterIP
  ingress_type: route
  route_host: awx.urskog.bot.nu
  route_tls_termination_mechanism: Edge
  route_tls_secret: ssl-cert-production
