apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/urskog84/awx-operator.git
    targetRevision: master
    path: awx-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true