apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inflxudb
  namespace: inflxudb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/urskog84/awx-operator.git
    targetRevision: main
    path: inflxudb
  destination:
    server: https://kubernetes.default.svc
    namespace: influxdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true