---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
type: Opaque
stringData:
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: urskog84
  INFLUXDB_DB: influx
  INFLUXDB_USER: user
  INFLUXDB_USER_PASSWORD: urskog84