apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-staging
  namespace: default
spec:
  secretName: ssl-cert-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: urskog.bot.nu
  dnsNames:
    - urskog.bot.nu
    - kuard.urskog.bot.nu
    - argo.urskog.bot.nu
    - awx.urskog.bot.nu
