apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-production
  namespace: default
spec:
  secretName: ssl-cert-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: urskog.bot.nu
  dnsNames:
    - urskog.bot.nu
    - kuard.urskog.bot.nu
    - argo.urskog.bot.nu
